---
- name: Template zabbix agent service
  ansible.builtin.template:
    src: zabbix_agent.service.j2
    dest: /etc/systemd/system/{{ zabbix_agent_service_name }}.service
    owner: "{{ zabbix_user }}"
    group: "{{ zabbix_group }}"
    mode: "0644"
  notify:
    - Restart zabbix agent
