---
- name: Install haproxy
  ansible.builtin.package:
    name: haproxy
    state: present

- name: Template haproxy configuration
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: '0644'

- name: Start haproxy
  ansible.builtin.systemd:
    name: haproxy
    state: restarted
    enabled: true
    daemon_reload: true

- name: Install keepalived
  ansible.builtin.package:
    name: keepalived
    state: present

- name: Template keepalived configuration
  ansible.builtin.template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    mode: '0644'

- name: Start keepalived
  ansible.builtin.systemd:
    name: keepalived
    state: restarted
    enabled: true
    daemon_reload: true
