---
# tasks file for ansible-zabbix
- name: Create Zabbix user
  ansible.builtin.include_tasks:
    file: user.yml

- name: Configure postgres server
  ansible.builtin.include_tasks:
    file: postgres.yml
  when: zabbix_database == "postgres"

# - name: Ensure mysql is up
#   ansible.builtin.include_tasks:
#     file: mysql.yml
#   when: zabbix_database == "mysql"

- name: Configure zabbix server
  ansible.builtin.include_tasks:
    file: server.yml

- name: Configure zabbix web ui
  ansible.builtin.include_tasks:
    file: ui.yml

- name: Configure zabbix agent
  ansible.builtin.include_tasks:
    file: agent.yml
