---
- name: Create Zabbix user
  ansible.builtin.include_tasks:
    file: user.yml

- name: Configure postgres server
  ansible.builtin.include_tasks:
    file: postgres.yml
  when: "'postgres' in group_names"

- name: Configure zabbix server
  ansible.builtin.include_tasks:
    file: server.yml
  when: "'zabbix_server' in group_names"

- name: Configure zabbix web ui
  ansible.builtin.include_tasks:
    file: ui.yml
  when: "'zabbix_server' in group_names"

- name: Configure zabbix agent
  ansible.builtin.include_tasks:
    file: agent.yml

- name: Configure haproxy and keepalived
  ansible.builtin.include_tasks:
    file: haproxy-keepalived.yml
  when: "'zabbix_server' in group_names and groups['zabbix_server'] | length > 1"
