---
# tasks file for ansible-zabbix
- name: Create Zabbix user
  ansible.builtin.include_tasks:
    file: user.yml

- name: Configure postgres server
  ansible.builtin.include_tasks:
    file: postgres.yml
  # when: zabbix_database == "postgres"
  when: "'zabbix_server' in group_names"

- name: Configure zabbix server
  ansible.builtin.include_tasks:
    file: server.yml
  when: "'zabbix_server' in group_names"

- name: Configure zabbix web ui
  ansible.builtin.include_tasks:
    file: ui.yml
  when: "'zabbix_server' in group_names"

- name: Configure zabbix agent
  ansible.builtin.include_tasks:
    file: agent.yml
