---
# tasks file for ansible-zabbix
- name: Ensure Zabbix user exists
  ansible.builtin.include_tasks:
    file: user.yml

- name: Ensure postgres is up
  ansible.builtin.include_tasks:
    file: postgres.yml
  when: zabbix_database == "postgres"

# - name: Ensure mysql is up
#   ansible.builtin.include_tasks:
#     file: mysql.yml
#   when: zabbix_database == "mysql"

- name: Ensure zabbix server is up
  ansible.builtin.include_tasks:
    file: server.yml

- name: Ensure zabbix ui is up
  ansible.builtin.include_tasks:
    file: ui.yml
