---
- name: Template zabbix server service
  ansible.builtin.template:
    src: zabbix_server.service.j2
    dest: /etc/systemd/system/{{ zabbix_server_service_name }}.service
    owner: "{{ zabbix_user }}"
    group: "{{ zabbix_group }}"
    mode: "0644"
  notify:
    - Restart zabbix server
