---
- name: Template zabbix web ui service
  ansible.builtin.template:
    src: zabbix_ui.service.j2
    dest: /etc/systemd/system/{{ zabbix_web_service_name }}.service
    owner: "{{ zabbix_user }}"
    group: "{{ zabbix_group }}"
    mode: "0644"
  notify:
    - Restart zabbix ui
